### ISSUE TITLE
Unable to add MobileCenter

### ISSUE THREAD

**Issue by sandyr39** [Microsoft/mobile-center-sdk-ios#189]
<img width="424" alt="screen shot 2016-11-24 at 2 32 17 pm" src="https://cloud.githubusercontent.com/assets/3636547/20592322/d2c7ef38-b252-11e6-9b8b-46218871bbad.png">

**Comment by vineetchoudhary** [comment]
Please use this podfile

```ruby
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'YOUR_TARGET' do
    pod 'MobileCenter'
end
```

- `inhibit_all_warnings!`
    > Turn off warnings for CocoaPods

 - `use_frameworks!`
    > You can make CocoaPods integrate to your project via frameworks instead of static libraries by specifying use_frameworks!. If that's not present, you won't be able to integrate dependencies, if you depend on a pod which includes Swift source code. This is an all or nothing approach per integrated targets, because we can't ensure to properly build frameworks, whose transitive dependencies are static libraries. This release goes along with probably one of the most drastic changes of the whole project, which includes CocoaPods itself, but also required similar changes to Xcodeproj as well.

`use_frameworks!` was added in CocoaPods 0.36.0

**Comment by TroubleMakerBen** [comment]
@sandyr39 did running 'pod repo update' solve the issue for you?

**Comment by TroubleMakerBen** [comment]
Closing this issue as we haven't heard from you. Feel free to open it again at a later time. =)
