### ISSUE TITLE
MobileCenterCrashes not found. 

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/mobile-center-sdk-ios#208]
Hi, 
I am trying to build my React Native project but it fails.  I added all the frameworks for crashes and analytics.  Do I actually need to do something with them in xcode?

I mainly am just writing JavaScript and not adding Native modules.  

Tried to remove those frameworks from the xcode project but unable to get xcode to compile again due to the error.

Here is the error I was having, even though I had added those frameworks.

▸ Check Dependencies
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/ci/agent/vstsagent/_work/1/output/build/build.obj/RNCrashes.build/Debug-iphoneos/RNCrashes.build/Objects-normal/armv7/RNCrashes.o RNCrashes/RNCrashes.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
▸ Building RCTLinking/RCTLinking [Debug]
▸ Check Dependencies
▸ Building library libRCTLinking.a
▸ Building library libRCTLinking.a
▸ Building RNCrashes/RNCrashes [Debug]
▸ Check Dependencies
▸ Compiling RNCrashes.m

❌  /Users/ci/agent/vstsagent/_work/1/s/node_modules/mobile-center-crashes/ios/RNCrashes/RNCrashesDelegate.h:3:9: module 'MobileCenterCrashes' not found

@import MobileCenterCrashes;
 ~~~~~~~^~~~~~~~~~~~~~~~~~~

Thanks

**Comment by jrmcdona** [comment]
Here is pic of the project and the error in xcode.  Crashes and Analytics are also both linked using the linked command.

<img width="748" alt="screen shot 2016-12-11 at 5 53 26 pm" src="https://cloud.githubusercontent.com/assets/4327773/21084554/d5d4ab3c-bfca-11e6-81c1-e2ea76d7ef3d.png">

**Comment by TroubleMakerBen** [comment]
Hey @jrmcdona,

As you have a react native project, you should use [our sdk for react tative](https://github.com/Microsoft/mobile-center-sdk-react-native). Or are you already using this?
if so, please open an issue over there. Thanks!

**Comment by TroubleMakerBen** [comment]
I'm leaving this open some more, in case you haven't seen my comment here. I will close the issue in a few days if we don't hear from you.

**Comment by jrmcdona** [comment]
Will do!  Thanks

**Comment by nechmads** [comment]
I'm using the SDK. I followed the exact instructions and still getting this error :(

**Comment by ricklove** [comment]
I also found this page in the top of the search results, so I wanted to add my solution...

After digging in the source code for the react-native link command I found the cause was because the name in package.json must match the dir name in the iOS folder:

I was using the ReactXP Hello World Sample as a boilerplate and had to do the following:

- In `package.json`
    - rename `rxp-hello-world` to `rxphelloworld`

After that the `react-native link mobile-center-crashes` command worked.
