### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by sopaco** [Microsoft/mobile-center-sdk-ios#580]
due to uncaught exception 'NSInvalidArgumentException', reason: '-[MSWrapperSdk initWithWrapperSdkVersion:wrapperSdkName:liveUpdateReleaseLabel:liveUpdateDeploymentKey:liveUpdatePackageHash:]: unrecognized selector sent to instance 0x618000268c00'
```object-c
[RNCrashes registerWithCrashDelegate: [[RNCrashesDelegateAlwaysSend alloc] init]];  // Initialize Mobile Center crashes

  [RNAnalytics registerWithInitiallyEnabled:true];  // Initialize Mobile Center analytics
```

**Comment by jaelim-ms** [comment]
@sopaco 
I'm closing this and created a new issue on React Native SDK [#37](https://github.com/Microsoft/mobile-center-sdk-react-native/issues/37) so we can track the issue where it belongs.
Thanks for reporting the issue, we will investigate it quite soon.
