### ISSUE TITLE
MSDistribute.open(url: String) does not return Bool in Swift

### ISSUE THREAD

**Issue by dvdsgl** [Microsoft/mobile-center-sdk-ios#581]
The Objective-C method has signature:

```objc
+(BOOL)openURL:(NSString *)url;
```

But the Swift signature appears to be

```swift
open class func open(_ url: URL)
```

Both should return `Bool`.

**Comment by lumaxis** [comment]
@dvdsgl The Swift signatures are auto-generated from the Objective-C code by Apple's tooling. Where did you see that Swift version you posted? I couldn't find it.

**Comment by dvdsgl** [comment]
This is the signature for the method in Swift that I get inside of Xcode.

![image](https://cloud.githubusercontent.com/assets/108197/26745414/3a87edd0-479f-11e7-9134-fd6fa6495f30.png)

Assigning the result of this call to a variable shows its type to be `Void`:

![image](https://cloud.githubusercontent.com/assets/108197/26745450/701e91ce-479f-11e7-9053-bb2a274d4da9.png)

**Comment by lumaxis** [comment]
@dvdsgl I think you are using an outdated version of the SDK, the return type was fixed 2 weeks ago.

**Comment by dvdsgl** [comment]
Confirming that this is fixed!
