### ISSUE TITLE
Can not enable in-app updates

### ISSUE THREAD

**Issue by Cooie** [Microsoft/mobile-center-sdk-ios#721]
I followed the [doc](https://docs.microsoft.com/en-us/mobile-center/sdk/distribute/ios) to add in-app updates to my app and distributed the build in Mobile Center portal. But after installing the app by the link from the e-mail that Mobile Center sent me and opening it, the browser just display `Fail to enable in-app updates. Reinstall the app from Mobile Center to enable them`. I had also tried to reinstall the app but didn't work.

Did I do something wrong?

**Comment by jaelim-ms** [comment]
The Distribute service relies on Safari, if your Safari is Private Browsing Mode, it will fail. Can you try again?

**Comment by Cooie** [comment]
My safari is not in Private Browser Mode, because if so, I can't even download the app. The problem is every time when I launch the app, it just show:

![img_0802](https://user-images.githubusercontent.com/29054176/29711995-2af8897a-89ca-11e7-8ef5-18fda9413dbc.PNG)

Is there something wrong? Is there an API to manually query if there is a new release in Mobile Center?

**Comment by jaelim-ms** [comment]
After digging into the issue, we found that the link that you used is for public groups.

Did you turn on "Allow public access" when you create a group on MobileCenter portal? If this is the case, unfortunately the SDK doesn't support public group yet. I apologize for any confusions but this feature is scheduled to be delivered in the next week. Please wait until you have a new release.

If the link that you installed your app is from private group, please let us know.

**Comment by Cooie** [comment]
Like you said, "Allow public access" is on in the test group. I turned off it and in-app updates work as  expected.

**Comment by Cooie** [comment]
One more thing, how can I get notified when a new SDK release is delivered?

**Comment by jaelim-ms** [comment]
Sorry but we don't have any notifications for new version update.
MobileCenter is in preview and we are pretty fast paced updating the SDK. I recommend you to check the latest version every 1-2 weeks. You can go to [GitHub release](https://github.com/Microsoft/mobile-center-sdk-ios/releases) or run `pod update` to get the latest SDK.

**Comment by jaelim-ms** [comment]
The new release is ready now. Closing this ticket.
