### ISSUE TITLE
Linker error when integrating with pods 

### ISSUE THREAD

**Issue by joeboyscout04** [Microsoft/mobile-center-sdk-ios#778]
Hi, I'm trying to integrate and start MobileSDK into my project both via pods and copying frameworks manually to the project. However, every time when I build it complains about missing symbols both for x86_64 and arm64 arch:

Showing All Messages
"_OBJC_CLASS_$_MSMobileCenter", referenced from:
objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
I've tried to build both with Xcode 9 and 8 and result is the same.

**Comment by jaelim-ms** [comment]
What version if the SDK are you using now?

**Comment by jaelim-ms** [comment]
Do you have `MobileCenter.framework` in your project?

**Comment by TroubleMakerBen** [comment]
Hey @joeboyscout04,

Were you able to resolve the issue? Please let us know, we'd love to help!

Benjamin

**Comment by TroubleMakerBen** [comment]
Hey, we haven't heard from you in a while. I'm closing this issue.
